### ISSUE TITLE
Docstring notation in condCovEst_wdiag

### ISSUE THREAD

**Issue by gapatron** [andrew-saydjari/CloudCovErr.jl#16]
In script perstar.jl, condCovEst_wdiag, km refers to masked pixels, unlike what the docstring reads (line 141). 

Since

`k = .! km`

Then k should be unmasked pixels. Also, k being unmasked is consistent with notation in paper.

Best,
Gabriel

**Comment by andrew-saydjari** [comment]
Hi Gabriel,

Thanks for catching the mistake in the docstring. You are right. I will fix momentarily.

In case it is useful, historical context for the reason the identity of the argument changed over the course of the project was to handle cases where we want to mask, but not interpolate pixels (the black regions in the corners of Figure 4 of the paper).

Best,
Andrew
